### ISSUE TITLE
omg bug bug bug

### ISSUE THREAD

**Issue by exception** [Phineas/cloudbleed-search#2]
![retard](http://i.giphy.com/aSTJbOerwCKqc.gif)

**Comment by MylesDev** [comment]
This is the most relevant issue I've ever seen. Because of the GIF, this issue should be taken on quickly and fixed/rolled out straight away to protect the security of our users.

**Comment by Phineas** [comment]
I agree, I will attempt to fix ASAP. Thanks.

**Comment by Phineas** [comment]
Fixed.
